# These are supported funding model platforms

github: [batuhan-basoglu] # Replace with up to 4 GitHub Sponsors-enabled usernames e.g., [user1, user2]
liberapay: batuhan-basoglu # Replace with a single Liberapay username
